db-uri = "postgres://radumeleru@localhost:5432/voost_vision"
db-schema = "public"
db-anon-role = "web_anon"
server-port = 54321
server-host = "localhost"
jwt-secret = "voost-vision-local-dev-secret-32chars"
